name: daily-cron
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          curl --request POST \
          --url 'https://serverless-functions-kohl.vercel.app/api/young/wallet/balance' \
          --header 'Authorization: Bearer $env:API_SECRET_KEY'
