name: daily-currencies
on:
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call currencies API
        run: |
          curl --request POST \
          --url 'https://serverless-functions-kohl.vercel.app/api/young/currencies/currencies' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' -o response.json
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Currencies"
          body: "Cron job ran successfully"
          html_body: file://response.json
          to: ${{ secrets.TO_EMAIL_USERNAME }}
          from: ${{ secrets.FROM_EMAIL_USERNAME }}
