name: recurring-order-BTC
on:
  schedule:
#    - cron: '0 9 1 * *'
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      VOLUME: 25
    steps:
      - name: Call order API
        run: |
          curl --request POST \
          --url 'https://serverless-functions-kohl.vercel.app/api/young/order/BTC?volume=$VOLUME' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Order Recurring BTC"
          body: "You bought $VOLUME € of BTC"
          to: ${{ secrets.TO_EMAIL_USERNAME }}
          from: ${{ secrets.FROM_EMAIL_USERNAME }}
