name: recurring-order-BTC
on:
  schedule:
    - cron: '0 2 1,15 * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      VOLUME: 0.0007
    steps:
      - name: Call order API
        run: |
          curl --request POST \
          --url 'https://serverless-functions-kohl.vercel.app/api/young/order/BTC?volume=${{ env.VOLUME }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
