name: Share data between jobs

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Get currencies
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl --request POST \
          --url 'https://serverless-functions-kohl.vercel.app/api/young/currencies/currencies' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' > currencies.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: currencies
          path: currencies.txt

  job_2:
    name: Display results
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: currencies
      - name: Print the final result
        shell: bash
        run: |
          value=`cat currencies.txt`
          echo The result is: $value
